### ISSUE TITLE
Organize tutorials

### ISSUE THREAD

**Issue by AleMorales** [VirtualPlantLab/VPLDocs#2]
The list of tutorials and how-to guide is growing but there is not much structure (they are dumped on the same folder) and there is no overview of what each of them contains. Possible improvements (they are not mutually exclusive):

- Organize the tutorials by folders
- Provided an initial page listing the tutorials and briefly explaining their contents
- Provide a tldr at the top of each tutorial so that a reader can judge whether it is worth reading a tutorial

**Comment by anaIFernst** [comment]
Create consistent tldr for each tutorial
